name: Start-ROM
on:
  push:
    branches:
      - master
  workflow_dispatch:
    
env: 
  TZ: Asia/Shanghai
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
       - name: Checkout
         uses: actions/checkout@master
         
       - name: Initializing the environment
         run: |
           cd $GITHUB_WORKSPACE/tool
           sudo -s bash ./Script/Setup.sh
         
       - name: Download Rom
         run: |
           cd $GITHUB_WORKSPACE/tool
           sudo -s bash ./Script/Download.sh
         
       - name: Start working on Rom & Upload Rom
         run: |
           cd $GITHUB_WORKSPACE/tool
           sudo -s bash tool.sh
